article: https://www.hackster.io/152814/smart-wireless-hardwario-iot-kit-mp3-player-765d86
articles:
  - title: Smart Wireless HARDWARIO IoT Kit MP3 Player
    url: https://www.hackster.io/152814/smart-wireless-hardwario-iot-kit-mp3-player-765d86
    description: With this project you can play any sound from your SD card on your audio system. Only wire you will need is 3.5mm jack.
    images:
      - url: https://hackster.imgix.net/uploads/attachments/1050331/_kyWExBMKLd.blob?auto=compress%2Cformat&w=900&h=675&fit=min
assembly:
  - name: HARDWARIO Core Module
  - name: HARDWARIO Power Module
  - name: YX5300 UART MP3 Player
